"""Public, server-rendered bilingual product pages; no account or model access."""
import json
from html import escape
from .product_showcase import FEATURES, feature_gallery, showcase_note, review_updates
from fastapi.responses import HTMLResponse, Response, RedirectResponse

ORIGIN = 'https://openharvey.com'


def register_marketing(app, root):
    def page(en=False, section='home'):
        def t(zh, english): return english if en else zh
        prefix = '/en' if en else ''
        home = prefix or '/'
        language_query = '?lang=en' if en else ''
        path = home if section == 'home' else prefix + '/' + section
        other = ('' if en else '/en') + (('/' + section) if section != 'home' else '') or '/'
        titles = {'features': t('产品亮点与实景演示 | OpenHarvey', 'Product Features & Screenshots | OpenHarvey'), 'home': t('OpenHarvey · 开源合同审查与标书 AI 工作台', 'OpenHarvey — Open-Source AI Contract Review'),
                  'security': t('安全与数据边界 | OpenHarvey', 'Security & Data Boundaries | OpenHarvey'),
                  'open-source': t('开源与自托管 | OpenHarvey', 'Open Source & Self-hosting | OpenHarvey'),
                  'harvey-alternative': t('面向合同审查的开源 Harvey 替代方案 | OpenHarvey', 'Open-Source Harvey Alternative for Contracts | OpenHarvey')}
        descriptions = {
            'home': t(
                'OpenHarvey（Open Harvey）是开源合同审查与标书 AI 工作台，支持个人记忆、DOCX 审改批注、原文溯源、自定义风险库和自托管。',
                'OpenHarvey (Open Harvey) is an open-source AI contract review and tender workspace with personal memory, DOCX review, comments, citations and self-hosting.'),
            'security': t(
                '了解 OpenHarvey 如何处理合同数据、E2B 沙箱执行、模型凭据、持久化、删除、备份与自托管边界。',
                'Learn how OpenHarvey handles contract data, sandboxed agent execution, model credentials, storage, deletion, backups and self-hosting boundaries.'),
            'open-source': t(
                '查看 OpenHarvey 开源合同 AI 工作台的 AGPL 许可证、系统架构、自托管方式、外部依赖与部署指南。',
                "Explore OpenHarvey's AGPL-licensed contract AI workspace, architecture, self-hosting options, source code, dependencies and deployment guide."),
            'harvey-alternative': t(
                '寻找开源 Harvey 替代方案？了解 OpenHarvey 的合同审查、原文引用、自定义风险库、自托管方式、运行成本与适用范围。',
                "Explore OpenHarvey, an open-source Harvey alternative for contract review. See source citations, custom playbooks, self-hosting and operating costs."),
            'features': t(
                '查看 OpenHarvey 合同 AI 工作台实景：个人记忆、DOCX 审改批注、目录联动、版本管理、原文溯源与多格式产出。',
                "See OpenHarvey's contract AI workspace in action: personal memory, DOCX tracked changes, comments, version history and source-linked review.")}
        description = descriptions[section]
        schema = {'@context':'https://schema.org','@type':'WebSite','name':'OpenHarvey','alternateName':'Open Harvey','url':ORIGIN,'sameAs':['https://github.com/twonly/OpenHarvey'],'inLanguage':['zh-CN','en'],'description':description}
        zhurl = ORIGIN + ('/' if section=='home' else '/'+section)
        enurl = ORIGIN + '/en' + ('' if section=='home' else '/'+section)
        header = f'''<!doctype html><html lang="{'en' if en else 'zh-CN'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{titles[section]}</title><meta name="description" content="{description}"><meta name="robots" content="index,follow"><link rel="canonical" href="{ORIGIN+path}"><link rel="alternate" hreflang="zh-CN" href="{zhurl}"><link rel="alternate" hreflang="en" href="{enurl}"><link rel="alternate" hreflang="x-default" href="{zhurl}"><meta property="og:type" content="website"><meta property="og:site_name" content="OpenHarvey"><meta property="og:title" content="{titles[section]}"><meta property="og:description" content="{description}"><meta property="og:url" content="{ORIGIN+path}"><meta property="og:image" content="{ORIGIN}/static/brand/openharvey-social.png"><meta name="twitter:card" content="summary_large_image"><link rel="icon" type="image/svg+xml" href="/static/brand/openharvey.svg"><link rel="stylesheet" href="/static/openharvey.css?v=20260914-repo"><link rel="stylesheet" href="/static/showcase.css?v=20260922-review"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script><script defer src="/static/site-telemetry.js?v=20260914-1"></script></head><body><a class="skip" href="#main">{t('跳到正文','Skip to content')}</a><header><div class="wrap nav"><a class="brand" href="{home}"><img src="/static/brand/openharvey.svg" alt="" width="32" height="32">OpenHarvey</a><nav aria-label="{t('主导航','Main navigation')}"><a class="optional" href="{prefix}/features">{t('产品','Product')}</a><a class="optional" href="{prefix}/security">{t('安全','Security')}</a><a class="desktop" href="{prefix}/open-source">{t('开源','Open source')}</a><a href="{other}" lang="{'zh-CN' if en else 'en'}" hreflang="{'zh-CN' if en else 'en'}">{t('English','中文')}</a><a href="/spaces{language_query}">{t('进入工作台 ↗','Workspace ↗')}</a></nav></div></header>'''
        footer = f'''<footer><div class="wrap"><div class="footer-row"><a class="brand" href="{home}">OpenHarvey</a><nav aria-label="{t('页脚导航','Footer navigation')}"><a href="{prefix}/open-source">{t('开源与部署','Open source & deployment')}</a><a href="{prefix}/security">{t('安全与数据','Security & data')}</a><a href="{prefix}/harvey-alternative">{t("开源 Harvey 替代方案","Open-source Harvey alternative")}</a><a href="/guide{language_query}">{t('使用指南','Guide')}</a></nav></div><p>{t('OpenHarvey 是独立项目，与 Harvey AI Corp. 没有关联、授权或赞助关系。AI 输出需结合原文和专业判断核对。','OpenHarvey is an independent project, not affiliated with, endorsed by or sponsored by Harvey AI Corp. Review AI outputs against original sources and professional judgment.')}</p><p>© 2026 OpenHarvey · {t('中文首页 / English at /en · 工作台支持中英文界面。','Chinese and English website · The workspace supports English and Chinese interfaces.')}</p></div></footer></body></html>'''
        def card(number, title, content, extra=''):
            return f'<article class="card {extra}"><span class="num">{number}</span><h3>{title}</h3><p>{content}</p></article>'
        if section == 'home':
            features = [
                ('01 / DOCUMENT',t('一份合同，一个工作空间','One contract. One workspace.'),t('围绕主合同、招投标文件组织附件、会话与产出。阅读、追问、审查和修改共享明确的材料上下文，处理长文档时不用来回搬运片段。','Keep the primary agreement, tender documents, attachments, conversations and deliverables together. Read, ask, review and revise with the relevant document context.')),
                ('02 / EVIDENCE',t('点击判断，回到原文','From a finding to its source.'),t('回答与报告中的有效引用可以定位到对应文档页码或段落，高亮连续原文。主合同与附件分别标识，让事实、风险和建议都有可核对的出处。','Follow valid citations to the source page or paragraph, with continuous text highlighting. Distinguish the primary document from attachments and check the evidence behind a finding.')),
                ('03 / WORKSPACE',t('原文与产出，并排看','Read source and output side by side.'),t('原文阅读器、Agent 对话、成果预览在同一工作台联动。圈选条款提问，核对报告依据，比较修改建议，再继续当前任务。','Use a connected document reader, agent conversation and deliverable preview. Ask about selected clauses, verify report evidence and compare suggested revisions.')),
                ('04 / ARTIFACTS',t('交付形式，跟着任务走','Deliverables shaped by the task.'),t('从摘要、风险报告到条款对照、HTML 看板和结构化数据，支持多种产出物。已保存文件可预览或下载，格式以工作台实际支持范围为准。','Create summaries, risk reports, clause comparisons, HTML dashboards and structured data. Preview or download saved files in supported formats.')),
                ('05 / PLAYBOOKS',t('用你的方法和标准审查','Your methods. Your standards.'),t('Skills 定义步骤、资料与交付要求；风险库定义检查项、立场与判断基线。按个人业务场景调整，并保留执行时使用的配置版本。','Skills define methods, references and delivery requirements. Risk playbooks define checks and baselines, with configuration versions retained for execution.')),
                ('06 / AGENT',t('能读、能分析，也能执行','An agent that carries work through.'),t('基于 OpenCode 原生 Agent，按任务读取材料、调用工具并保存文件。可选择模型、扩展 Skills，查看工具执行和保存结果。','Built on native OpenCode agents to read documents, use tools and save results. Choose models, extend Skills and inspect tool execution and file receipts.'))]
            cards=''.join(card(*f) for f in features)
            body = f'''<main id="main"><section class="wrap hero"><div class="hero-top"><div><p class="eyebrow"><span class="dot"></span> {t('OpenHarvey · 开源合同审查与标书工作台','OpenHarvey · Open-source AI contract review')}</p><h1>{t('读懂每一份合同。<br>让判断<em>有据可依。</em>','Understand every contract.<br><em>Ground every decision.</em>')}</h1></div><div><p class="hero-description">{description}</p><div class="actions"><a class="btn" href="/demo{language_query}">{t('打开示例工作台 ↗','Try the workspace ↗')}</a><a class="btn light" href="{prefix}/open-source">{t('开源与自托管','Open source & self-hosting')}</a><a class="btn light repo-link" href="https://github.com/twonly/OpenHarvey" target="_blank" rel="noopener noreferrer" aria-label="{t('在 GitHub 查看 OpenHarvey 仓库（新窗口）','View OpenHarvey on GitHub (new tab)')}"><img src="/static/brand/github.svg" width="18" height="18" alt="">GitHub · OpenHarvey</a></div><p class="fine">{t('打开示例文档，开启独立试用空间。工作台支持中英文界面。','Start with a sample document in your own trial workspace. The workspace supports English and Chinese interfaces.')}</p></div></div><div class="tags"><span>{t('文档对象设计','Document-centered design')}</span><span>{t('原文定位联动','Linked source navigation')}</span><span>{t('多格式产出','Flexible deliverables')}</span><span>{t('Sandbox 执行隔离','Sandboxed execution')}</span></div>
<figure class="scene"><div class="scene-bar"><span>● ● ● &nbsp; OpenHarvey / Workspace</span><span>{t('从原文到判断，再到交付','SOURCE → FINDING → DELIVERABLE')}</span></div><div class="scene-grid"><aside class="scene-side"><b>{t('采购服务合同','Services agreement')}</b><p class="selected">{t('合同风险审查','Risk review')}</p><p>{t('付款条款修改','Payment revisions')}</p><small>{t('本次材料','DOCUMENTS')}</small><p>▤ {t('主合同.docx','Agreement.docx')}</p><p>▤ {t('技术附件.pdf','Specification.pdf')}</p><small>{t('已保存产出','DELIVERABLES')}</small><p>▤ {t('风险看板.html','Risk dashboard.html')}</p></aside><div class="source"><div class="paper"><small>SERVICE AGREEMENT / 03</small><h3>{t('采购服务合同','Services agreement')}</h3><p>{t('第五条 · 结算与付款','Clause 5 · Payment')}</p><p>{t('甲方应在收到合规发票并确认验收后，<mark>于九十日内支付相应服务费用。</mark>','Upon receipt of a valid invoice and acceptance of services, the customer shall <mark>pay the corresponding fees within ninety days.</mark>')}</p><div class="source-anchor">↗ {t('主合同 · 第 3 页 · 付款期限','Agreement · Page 3 · Payment term')}</div></div></div><div class="chat"><div class="question">{t('按我的风险库审查付款条款，做一份风险看板。','Review payment terms against my playbook and create a risk dashboard.')}</div><small>✓ {t('读取原文 → 对照标准 → 保存产出','Read source → Apply playbook → Save output')}</small><div class="finding"><b>{t('付款期限需协商','Payment term needs negotiation')}</b><p>{t('原文约定 90 日，示例基线为 30 日。建议缩短付款周期，并明确验收的触发条件。','The agreement specifies 90 days; the example baseline is 30. Consider negotiating a shorter term and clear acceptance conditions.')}</p><span class="citation">↗ {t('查看原文 · 第 3 页','View source · Page 3')}</span></div><div class="file"><span>▤ {t('付款风险看板.html','Payment risk dashboard.html')}</span><span>↗</span></div></div></div><figcaption class="scene-caption">{t('产品交互示意，非实际审查结果。进入示例工作台，使用文档体验阅读、追问与产出。','Workflow illustration, not an actual review result. Open the sample workspace to read, ask questions and create deliverables.')}</figcaption></figure></section>
<div class="wrap">{review_updates(en)}</div><section class="section"><div class="wrap"><p class="eyebrow">SEE IT IN THE WORKSPACE</p><h2>{t('产品亮点，看实际界面。','See the product in action.')}</h2><p class="intro">{t('原文溯源、灵活产出、个人风险清单、可扩展 Skills 和 BYOK，把合同工作串起来。','Source navigation, flexible deliverables, personal playbooks, extensible Skills and BYOK—connected in one workspace.')}</p>{feature_gallery(en,compact=True)}<a class="btn light" href="{prefix}/features">{t('查看五大亮点与完整截图 ↗','Explore all five features ↗')}</a></div></section>
<section class="section" id="product"><div class="wrap"><p class="eyebrow">BUILT AROUND THE DOCUMENT</p><h2>{t('合同工作，需要把上下文连起来。','Contract work depends on connected context.')}</h2><p class="intro">{t('合同、标书和附件具有条款、页码、版本与业务标准。OpenHarvey 把这些关系做进工作台，让阅读、判断、修改和交付形成连续的工作过程。','Contracts and tenders have clauses, pages, versions and business standards. OpenHarvey connects these relationships across reading, analysis, revision and delivery.')}</p><div class="grid">{cards}</div></div></section>
<section class="section"><div class="wrap"><p class="eyebrow">A PURPOSE-BUILT WORKFLOW</p><h2>{t('选择工具，从你每天处理的对象出发。','Choose a workspace around the work you do.')}</h2><p class="intro">{t('如果你正在比较豆包工作、WorkBuddy、千问办公等办公 Agent，可以用下面几个具体任务体验 OpenHarvey 的专门设计。这里展示本产品的工作方式，不对其他产品的能力作缺失判断。','If you are comparing general office agents, try these concrete workflows in OpenHarvey. These describe our design, without assuming other tools lack the same capabilities.')}</p><div class="compare"><table><thead><tr><th>{t('你的任务','Your task')}</th><th>{t('OpenHarvey 的工作方式','The OpenHarvey workflow')}</th></tr></thead><tbody><tr><td>{t('审查一份长合同与相关附件','Review a long agreement and attachments')}</td><td>{t('在合同空间组织主文档、附件与多个会话，保留材料和产出的关联。','Organize the primary source, attachments and multiple conversations in a contract workspace.')}</td></tr><tr><td>{t('核对某一项风险是否成立','Verify a specific finding')}</td><td>{t('从回答或报告中的有效引用回到对应原文，高亮页码或连续段落。','Follow a valid citation from the answer or report to highlighted source text.')}</td></tr><tr><td>{t('按自己的业务标准审查','Apply your business standards')}</td><td>{t('选择和维护 Skills、风险方案及立场，按本次配置执行。','Select Skills, risk playbooks and your party perspective for the task.')}</td></tr><tr><td>{t('把分析变成可交付成果','Turn analysis into deliverables')}</td><td>{t('按需求保存摘要、修改对照、HTML 报告或结构化数据，在原文旁预览并下载。','Save a summary, revision comparison, HTML report or structured data; preview it alongside the source.')}</td></tr></tbody></table></div></div></section>
<section class="section dark-band" id="sandbox"><div class="wrap"><p class="eyebrow">SANDBOX / PRIVACY / CONTROL</p><h2>{t('让 Agent 有执行空间，<br>也有明确的边界。','Room for agents to work.<br>Clear boundaries around execution.')}</h2><p class="intro">{t('云端模式在 E2B 沙箱中运行 OpenCode，配合账号权限、材料范围和持久化存储，控制执行与数据访问。','Cloud mode runs OpenCode in E2B sandboxes, alongside account permissions, document scopes and persistent storage.')}</p><div class="grid">{card('01',t('隔离执行','Isolated execution'),t('Agent 的工具与代码在云端沙箱中执行；应用按账号检查空间、会话和文件权限。','Agent tools and code run in cloud sandboxes. The application checks ownership of workspaces, conversations and files.'))}{card('02',t('控制材料与凭据','Control documents and credentials'),t('沙箱同步当前任务可访问的材料和规则。平台模型密钥保留在服务端，试用通过受限凭据调用。个人模型仍需按实际配置处理凭据。','Sandboxes receive accessible task materials and rules. Platform model keys stay server-side behind restricted trial credentials. Personal model credentials follow the selected configuration.'))}{card('03',t('保存成果，管理生命周期','Persist results, manage lifecycle'),t('正式成果保存到服务端持久存储；暂停或重建沙箱依赖检查点恢复。试用到期按系统规则撤销访问并清理数据。','Saved deliverables persist on the server. Sandbox recovery uses checkpoints. Expired trials are revoked and cleaned up according to system rules.'))}</div><p class="data-note">{t('数据路径：浏览器 → 应用服务与持久存储 → E2B 沙箱 → 所选模型服务。Sandbox 不等于离线处理、零数据外传或合规认证。自托管 Web 也不自动替换 E2B 或远程模型。','Data path: browser → application and storage → E2B sandbox → selected model service. Sandboxing does not mean offline processing, zero data transfer or compliance certification. Self-hosting the web application does not automatically replace E2B or remote models.')} <a href="{prefix}/security">{t('了解数据边界 ↗','Read the data boundaries ↗')}</a></p></div></section>
<section class="section" id="architecture"><div class="wrap split"><div><p class="eyebrow">POWERED BY OPENCODE</p><h2>{t('成熟的 Agent 底座，<br>面向合同的产品设计。','A flexible agent runtime.<br>A workspace built for contracts.')}</h2><p class="intro">{t('OpenCode 提供原生工具调用、Skills、会话和执行权限。OpenHarvey 在其上组织文档对象、原文定位、风险配置与产出交付，让开发者扩展方法，让业务用户专注任务。','OpenCode provides native tools, Skills, sessions and execution permissions. OpenHarvey adds document organization, source navigation, review configuration and deliverables.')}</p><p class="fine"><a href="https://opencode.ai/docs/skills/" target="_blank" rel="noopener">OpenCode Skills ↗</a> · <a href="{prefix}/open-source">{t('开源与架构说明 ↗','Open source & architecture ↗')}</a></p></div><div class="stack"><div><b>OpenHarvey</b><small>{t('文档 · 引用 · 风险 · 产出','Documents · Citations · Risks · Deliverables')}</small></div><div><b>OpenCode</b><small>{t('Agent · Skills · 工具 · 会话','Agents · Skills · Tools · Sessions')}</small></div><div><b>E2B / Runtime</b><small>{t('执行隔离 · 检查点 · 生命周期','Isolation · Checkpoints · Lifecycle')}</small></div><div><b>{t('模型与存储','Models & storage')}</b><small>{t('个人模型配置 · 持久成果','Personal model settings · Persistent results')}</small></div></div></div></section>
<section class="section"><div class="wrap faq"><p class="eyebrow">QUESTIONS, ANSWERED</p><h2>{t('开始前，你可能想知道。','Before you begin.')}</h2>'''
            questions=[(t('OpenHarvey 是什么？','What is OpenHarvey?'),description),
                       (t('支持哪些文件和产出？','Which documents and outputs are supported?'),t('输入支持 DOCX、文字 PDF、Markdown 和 TXT；扫描 PDF 需先 OCR。产出支持摘要、风险报告、修改对照及支持格式的自定义文件。预览与下载以实际文件和格式为准，不保证任意可执行文件都可在线运行。','Inputs include DOCX, text PDFs, Markdown and TXT. Scanned PDFs require OCR first. Outputs include summaries, risk reports, revision comparisons and custom files in supported formats; previews depend on the format.')),
                       (t('能服务英语用户吗？','Can English-speaking users use it?'),t('官网和工作台界面支持中文与英文。示例文件、已有回答与报告保留原有语言；Agent 工作语言策略及英语任务质量仍需单独验收。','The website and workspace interface support Chinese and English. Sample documents, existing answers and reports retain their original language. Agent language policies and English-task quality require separate validation.')),
                       (t('Sandbox 能保证绝对隐私吗？','Does sandboxing guarantee complete privacy?'),t('不能。Sandbox 负责执行隔离；文档仍可能由应用服务器、E2B 和所选模型服务处理。请根据部署方式和供应商条款判断适用的数据范围。','No. Sandboxes isolate execution; documents may still be processed by the application server, E2B and the selected model provider. Choose a deployment and providers appropriate to your data.')),
                       (t('与 Harvey 有什么关系？','Is OpenHarvey affiliated with Harvey?'),t('OpenHarvey 是独立项目，没有 Harvey 的授权、赞助或关联。当前专注合同与标书文档工作流，不宣称与 Harvey 全部能力相同。','OpenHarvey is independent and is not affiliated with, endorsed by or sponsored by Harvey. It focuses on contract and tender workflows and does not claim feature parity.'))]
            body+=''.join(f'<details><summary>{escape(q)}</summary><p>{escape(a)}</p></details>' for q,a in questions)
            faq={'@context':'https://schema.org','@type':'FAQPage','mainEntity':[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':a}} for q,a in questions]}
            body+=f'''</div></section><div class="wrap"><section class="closing"><div><h2>{t('下一份合同，从这里开始。','Start with your next contract.')}</h2><p>{t('先看真实示例，再带上你的原文和业务标准。','Explore an example, then bring your documents and playbook.')}</p></div><a class="btn" href="/demo{language_query}">{t('打开产品示例 ↗','Explore examples ↗')}</a></section></div></main><script type="application/ld+json">{json.dumps(faq,ensure_ascii=False)}</script>'''
        elif section=='features':
            labels=t(('原文溯源','灵活产出','风险清单','三大 Skills','试用与 BYOK'),('Source evidence','Deliverables','Playbooks','Three Skills','Trial & BYOK'))
            jump=''.join(f'<a href="#{feature["id"]}">{label}</a>' for feature,label in zip(FEATURES,labels))
            application={'@context':'https://schema.org','@type':'SoftwareApplication','name':'OpenHarvey','alternateName':'Open Harvey','url':ORIGIN,'sameAs':['https://github.com/twonly/OpenHarvey'],'applicationCategory':'BusinessApplication','operatingSystem':'Web','featureList':[f['en' if en else 'zh'][0] for f in FEATURES],'screenshot':[ORIGIN+'/static/product/'+f['image'] for f in FEATURES]}
            body=f'''<main id="main" class="wrap"><section class="showcase-intro"><p class="eyebrow">OPENHARVEY / IN PRACTICE</p><h1>{t('看得见依据，<br>交得出成果。','See the evidence.<br>Deliver the work.')}</h1><p class="intro">{t('不只是围绕文档聊天。让原文、判断、业务标准与产出在同一个工作台里连起来。以下五张产品实景，带你走完这条工作路径。','More than a chat beside a document. Connect sources, findings, business standards and deliverables in one workspace. Explore five views of the product below.')}</p><div class="showcase-cta"><a class="btn" href="/demo{language_query}">{t('免费体验示例 ↗','Try the sample workspace ↗')}</a><a class="btn light" href="https://github.com/twonly/OpenHarvey">{t('在 GitHub 查看源码','View source on GitHub')}</a></div><nav class="showcase-jump" aria-label="{t('产品亮点目录','Feature navigation')}">{jump}</nav></section>{review_updates(en)}{feature_gallery(en)}<p class="showcase-note">{showcase_note(en)}</p><div class="showcase-cta"><a class="btn" href="/demo{language_query}">{t('从一份示例合同开始 ↗','Start with a sample contract ↗')}</a><a class="btn light" href="/guide{language_query}">{t('查看完整使用指南','Read the guide')}</a></div></main><script type="application/ld+json">{json.dumps(application,ensure_ascii=False)}</script>'''
        else:
            if section=='security':
                article=t('''<p>OpenHarvey 的安全设计由执行隔离、访问控制、凭据管理与持久化共同组成。以下描述当前实现，不代表独立安全审计或合规认证。</p><h2>数据在哪里处理？</h2><p>上传的原件、解析文本、对话快照、成果和检查点由应用服务保存。云端执行时，任务材料会同步到 E2B，模型调用将相关上下文发送给所选供应商。当前托管版使用 Railway 持久卷保存业务数据，Supabase 提供登录身份认证。</p><h2>Sandbox 隔离什么？</h2><p>E2B 为 Agent 工具执行提供隔离环境；应用按用户权限限制材料、空间与文件访问。不同会话的材料权限由工作台管理。同一合同空间中的会话可能共用其运行环境，因此会话级材料规则不是独立操作系统隔离。</p><h2>凭据与访问</h2><p>平台模型真实密钥留在服务端，试用使用受限转发凭据。个人配置的模型需要运行时访问凭据；应用加密保存模型配置，部署者必须妥善保管解密主密钥。生产登录使用 Secure、HttpOnly Cookie。</p><h2>持久化、删除与备份</h2><p>成果保存回执确认服务端落盘。归档、最近删除、永久删除与试用到期清理是不同操作。沙箱销毁不自动删除服务端成果；持久卷也不等于独立备份。自托管者负责备份、恢复、保留策略和运行环境配置。</p><h2>自托管的边界</h2><p>自托管 Web 可以控制应用和存储部署位置。继续使用 E2B 或远程模型时，相关数据仍经过这些服务。单机本地运行模式不提供操作系统级多用户隔离；共享服务应使用受支持的隔离方案。</p><p>参考：<a href="https://e2b.dev/security">E2B 安全说明</a>、<a href="https://opencode.ai/docs/permissions/">OpenCode 权限文档</a>。</p>''','''<p>OpenHarvey combines execution isolation, access control, credential management and persistent storage. This describes the implementation, not an independent security audit or compliance certification.</p><h2>Where is data processed?</h2><p>The application stores source files, extracted text, conversation snapshots, deliverables and checkpoints. Cloud execution transfers task materials to E2B and relevant context to the selected model provider. The hosted deployment uses a Railway persistent volume for business data and Supabase for authentication.</p><h2>What does the sandbox isolate?</h2><p>E2B isolates agent tool execution. Application permissions control access to documents, workspaces and files. Conversations within a contract workspace may share its runtime, so conversation document policies are not separate operating-system isolation.</p><h2>Credentials and access</h2><p>Platform model keys remain server-side, with restricted credentials for trial inference. Personal models require runtime access to their credentials. Stored model configuration is encrypted; operators must protect the master key. Production sessions use Secure, HttpOnly cookies.</p><h2>Persistence, deletion and backups</h2><p>A save receipt confirms server persistence. Archiving, soft deletion, permanent deletion and trial expiry are different operations. Destroying a sandbox does not automatically delete server deliverables. Persistent storage does not replace independent backups.</p><h2>Self-hosting boundaries</h2><p>Self-hosting gives you control over application and storage deployment. If you keep using E2B or remote models, data still passes through those services. Local process mode does not provide operating-system isolation between users.</p><p>References: <a href="https://e2b.dev/security">E2B security</a> and <a href="https://opencode.ai/docs/permissions/">OpenCode permissions</a>.</p>''')
            elif section=='open-source':
                article=t('''<p>OpenHarvey 采用 AGPL-3.0-only 开放应用源码。<a href="https://github.com/twonly/OpenHarvey">在 GitHub 查看源码</a>，或阅读<a href="https://github.com/twonly/OpenHarvey/blob/main/docs/deployment.md">部署指南</a>。当前为早期预览版本。</p><h2>开源内容</h2><p>合同工作台源码、文档定位、产出管理、OpenCode 接入、公开 Skills、虚构示例风险库与部署说明。真实合同、账号数据、凭据、内部风险库和原开发仓库历史不属于公开内容。</p><h2>架构</h2><p>FastAPI 提供 Web 与业务 API；SQLite 与文件系统保存元数据和材料；OpenCode 执行 Agent 会话；云端模式使用 E2B。Supabase 登录、模型服务与 E2B 均为独立外部依赖，开源应用代码不意味着这些服务免费或可以离线使用。</p><h2>国际化路线</h2><p>第一步是中文主站与 /en 英文站。下一步将覆盖登录、合同空间、阅读器、对话、产出、设置和错误消息的英语界面，持久保存语言偏好，并验证英文合同及英文报告。不会用首页翻译代表全产品国际化。</p><h2>适用范围</h2><p>优先服务合同、招投标文档阅读、风险审查和交付。扫描件 OCR、司法管辖区知识库及法律研究覆盖不属于当前承诺。公开包提供虚构合同、示例风险库与自动化测试；真实模型调用需配置自己的服务。</p>''','''<p>OpenHarvey application code is available under AGPL-3.0-only. <a href="https://github.com/twonly/OpenHarvey">View the source on GitHub</a> or read the <a href="https://github.com/twonly/OpenHarvey/blob/main/docs/deployment.md">deployment guide</a>. This is an early preview release.</p><h2>What is included?</h2><p>The workspace source, citation navigation, deliverable management, OpenCode integration, public Skills, fictional risk examples and deployment documentation. Real contracts, account data, credentials, private playbooks and the original development repository history are excluded.</p><h2>Architecture</h2><p>FastAPI serves the application and business APIs. SQLite and the filesystem persist metadata and files. OpenCode executes agents; cloud mode uses E2B. Supabase authentication, model providers and E2B are separate dependencies. Open application code does not make those services free or offline.</p><h2>Internationalization roadmap</h2><p>The Chinese homepage and /en website are the first step. English workspace navigation, authentication, document reading, chat, artifacts, settings, errors and saved language preferences require further localization and English contract tests.</p><h2>Scope</h2><p>The initial focus is contract and tender review and delivery. Built-in OCR, jurisdiction-specific legal databases and comprehensive legal research are not promised. The distribution includes a fictional contract, sample playbooks and automated tests. Model execution requires your own provider setup.</p>''')
            else:
                article=t('''<p>OpenHarvey（Open Harvey）是面向合同审查与标书工作流的开源 Harvey 替代方案，提供原文引用、自定义风险库、多格式交付和自托管选项。它适合希望查看源码、配置模型并按自身业务标准处理文档的团队。</p><h2>如何与 Harvey 比较？</h2><p>Harvey 官网介绍了 Agents、Vault、Spaces、Knowledge 和 Contract Intelligence 等产品。OpenHarvey 当前聚焦合同空间、原文定位、可配置 Skills 与风险库、产出预览与下载。我们不宣称全面替代 Harvey，也没有开展同条件性能或准确率比较。</p><h2>可核对的选择标准</h2><p>考虑你是否需要自行部署应用、查看源码、配置模型和业务规则，以及是否需要合同与报告间的引用联动。评估时也应验证英文任务、身份认证、运行费用、数据处理服务与备份能力。公开发行状态见开源页面。</p><h2>对“开源”的准确理解</h2><p>Harvey 也发布了开源法律 Agent 评测和开放权重研究模型；不能笼统声称它没有任何开源内容。OpenHarvey 开放的是这套合同工作台应用代码。</p><p>来源：<a href="https://www.harvey.ai/">Harvey 官方产品介绍</a>、<a href="https://www.harvey.ai/blog/introducing-harveys-legal-agent-benchmark">Legal Agent Benchmark</a>。核对日期：2026-09-13。</p>''','''<p>OpenHarvey (Open Harvey) is an open-source Harvey alternative focused on contract review and tender workflows, with source-linked findings, configurable playbooks and self-hosting options. It serves teams that want to inspect the code, choose models and apply their own business standards.</p><h2>How should it be compared with Harvey?</h2><p>Harvey describes Agents, Vault, Spaces, Knowledge and Contract Intelligence on its website. OpenHarvey focuses on contract workspaces, source navigation, configurable Skills and playbooks, and deliverable previews and downloads. It does not claim feature parity, and no controlled performance or accuracy comparison has been conducted.</p><h2>What should teams evaluate?</h2><p>Consider application self-hosting, source access, model choice, configurable business rules and navigation between findings and source documents. Also evaluate English workflows, authentication, operational costs, third-party data processing and backups. See the open-source page for release status.</p><h2>Be precise about open source</h2><p>Harvey has also released an open-source legal agent benchmark and open-weight model research. It would be inaccurate to say that Harvey has no open-source work. OpenHarvey publishes the application code for its contract workspace.</p><p>Sources: <a href="https://www.harvey.ai/">Harvey product website</a> and <a href="https://www.harvey.ai/blog/introducing-harveys-legal-agent-benchmark">Legal Agent Benchmark</a>. Checked: September 13, 2026.</p>''')
                article += t('<h2>用一份合同验证是否适合</h2><p>打开示例工作台，选择供应商立场，要求“按我的风险库审查付款与验收条款，逐项给出原文依据、风险说明和修改建议，并保存报告”。核对引用能否回到原文，再检查保存文件与下载内容。示例风险标准为虚构数据，需替换为自己的业务规则。</p><h2>部署与运行费用</h2><p>应用源码采用 AGPL-3.0-only 许可证。可以在可信单用户电脑上运行，或按部署指南配置云端服务。运行预算包括应用托管与存储、模型 API、E2B 沙箱及所选认证服务；具体费用取决于供应商与使用量。自托管应用不会自动实现离线推理，远程模型和沙箱仍可能处理任务材料。</p><h2>哪些团队更适合？</h2><p>优先考虑需要合同与标书阅读、原文核对、自定义审查规则和文件交付的采购、销售、法务及交付团队。若核心需求是完整法律数据库、特定司法管辖区研究或已经验收的企业合规认证，需要另行评估产品与服务。</p><p><a href="/demo">打开示例工作台</a> · <a href="https://github.com/twonly/OpenHarvey/blob/main/docs/deployment.md">阅读部署指南</a> · <a href="/security">了解数据边界</a></p><h2>查看实际工作台</h2><p>以下为项目方提供的界面截图；展示产品交互，不代表独立验证的审查结果。</p>','<h2>Evaluate it with one contract</h2><p>Open the sample workspace, choose the supplier perspective and ask: “Review payment and acceptance terms against my playbook. Include source evidence, risk explanations and proposed revisions, and save a report.” Follow citations back to the original text, then check the saved file and download. Sample risk baselines are fictional; replace them with your business rules.</p><h2>Self-hosting and operating costs</h2><p>The application code is licensed under AGPL-3.0-only. Run it on a trusted single-user computer or configure cloud services using the deployment guide. Budget for application hosting and storage, model APIs, E2B sandboxes and your selected authentication service. Costs depend on providers and usage. Self-hosting the application does not automatically provide offline inference: remote models and sandboxes may still process task materials.</p><h2>Who is it for?</h2><p>Consider OpenHarvey for procurement, sales, legal and delivery teams working with contracts, tender documents, source verification, custom review rules and saved deliverables. Comprehensive legal databases, jurisdiction-specific research and independently verified enterprise compliance certifications require separate evaluation.</p><p><a href="/demo?lang=en">Try the sample workspace</a> · <a href="https://github.com/twonly/OpenHarvey/blob/main/docs/deployment.md">Read the deployment guide</a> · <a href="/en/security">Review data boundaries</a></p><h2>See the actual workspace</h2><p>These owner-supplied screenshots illustrate the interface, not independently verified review results.</p>')
                article += feature_gallery(en, compact=True)
            body=f'<main id="main" class="wrap reading"><p class="eyebrow">OPENHARVEY / {section.upper()}</p><h1>{titles[section].split(" | ")[0]}</h1>{article}<p><a href="{home}">{t("返回首页","Back to home")}</a> · <a href="{prefix}/open-source">{t("开源状态","Release status")}</a></p></main>'
        if section in {'home', 'features'}:
            connector = f'''<section class="wrap section" id="feishu-lark"><p class="eyebrow">FEISHU / LARK</p><h2>{t('让合同工作接上企业知识与协作','Connect contract work with company knowledge')}</h2><p class="intro">{t('连接飞书 / Lark，把文档、知识库和多维表格带进合同与标书任务。通过官方网页授权，以当前用户的权限读取资料、保存成果和执行明确指定的操作。','Connect Feishu / Lark documents, wikis and Base to contract and tender tasks. Authorize through the official website to read sources, save results and carry out requested actions within your permissions.')}</p><div class="grid">{card('01 / POLICY',t('按真实业务背景审合同','Review with business context'),t('查找渠道销售政策，结合合同中的直销或渠道属性，核对账期、授权范围与返利条件，并给出制度来源。','Find channel sales policies and compare payment terms, authorization scope and rebates with the contract’s direct or channel sales context. Cite the policy sources.'))}{card('02 / TENDER',t('把知识库用在投标准备中','Bring company knowledge into tender preparation'),t('结合标书要求与可访问的产品、交付资料，整理响应要点、差异与待澄清事项，按要求保存协作文档。','Compare tender requirements with accessible product and delivery materials. Prepare response points, gaps and questions, then save a shared document when requested.'))}{card('03 / FOLLOW-UP',t('报告、台账与协作衔接','Connect reports, registers and follow-up'),t('保存风险报告并返回真实链接；先读取多维表格字段，再更新指定记录。明确要求通知时，搜索联系人并以你的身份发送消息。','Save a risk report with its actual link. Read Base fields before updating the specified record. When explicitly asked to notify someone, find the contact and send a message as you.'))}</div><p>{t('每个工作台账号单独授权，合同空间使用各自的 E2B 沙箱。应用权限与企业审批仍然适用；消息发送和联系人搜索需额外授权。飞书文档与台账读写已完成真实链路验证，Lark 国际版和消息发送尚待真实账号验收。','Each workspace account authorizes separately, and contract spaces use their own E2B sandboxes. App permissions and organization approval still apply; messaging and contact search need additional consent. Feishu document and Base workflows have been exercised end to end; Lark international and messaging await live-account acceptance.')}</p><p><a class="button" href="/connectors{language_query}">{t('连接飞书 / Lark →','Connect Feishu / Lark →')}</a></p></section>'''
            body=body.replace('</main>',connector+'</main>')
        return HTMLResponse(header+body+footer)

    @app.get('/en')
    async def english_home(): return page(True)

    @app.get('/en/')
    async def english_slash(): return RedirectResponse('/en',status_code=308)

    for section in ('security','open-source','harvey-alternative','features'):
        def endpoint(en, name):
            async def render(): return page(en,name)
            return render
        app.add_api_route('/'+section,endpoint(False,section),methods=['GET'])
        app.add_api_route('/en/'+section,endpoint(True,section),methods=['GET'])

    @app.get('/robots.txt')
    async def robots():
        paths=('/api/','/agent','/spaces','/login','/auth/','/config','/model','/skills','/risks','/members','/traces','/trial-model/')
        return Response('User-agent: *\nAllow: /\n'+''.join('Disallow: '+p+'\n' for p in paths)+'Sitemap: '+ORIGIN+'/sitemap.xml\n',media_type='text/plain')

    @app.get('/sitemap.xml')
    async def sitemap():
        paths=['/','/en']+[p+'/'+s for s in ('security','open-source','harvey-alternative','features') for p in ('','/en')]
        return Response('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+ORIGIN+p+'</loc></url>' for p in paths)+'</urlset>',media_type='application/xml')

    @app.get('/llms.txt')
    async def llms():
        return Response('# OpenHarvey\n\nIndependent AI workspace for contract and tender documents.\n\n- [中文]('+ORIGIN+'/)\n- [English]('+ORIGIN+'/en)\n- [Features and screenshots]('+ORIGIN+'/en/features)\n- [Security]('+ORIGIN+'/en/security)\n- [Release status]('+ORIGIN+'/en/open-source)\n\nThe workspace supports English and Chinese interfaces. OpenHarvey is not affiliated with Harvey AI Corp.\n',media_type='text/plain')

    return page
